### ISSUE TITLE
Proposal to add newlines

### ISSUE THREAD

**Issue by DanielRuf** [EFForg/yaya#20]
Currently the warnings are directly after the `git clone` output because there is no newline character.

<img width="514" alt="Bildschirmfoto 2020-11-24 um 20 37 34" src="https://user-images.githubusercontent.com/827205/100143099-173fe400-2e95-11eb-8830-46ea9d2dcd22.png">

I think the following would be better:

<img width="951" alt="Bildschirmfoto 2020-11-24 um 20 36 43" src="https://user-images.githubusercontent.com/827205/100143125-2161e280-2e95-11eb-9e8d-0cd42c6576ca.png">
<img width="943" alt="Bildschirmfoto 2020-11-24 um 20 37 02" src="https://user-images.githubusercontent.com/827205/100143128-22930f80-2e95-11eb-9094-a3adb6cf204f.png">
<img width="468" alt="Bildschirmfoto 2020-11-24 um 20 37 52" src="https://user-images.githubusercontent.com/827205/100143130-232ba600-2e95-11eb-96b9-ab635780eb9a.png">

What do you think? I can provide a PR if this change makes sense.

**Comment by cooperq** [comment]
yea I think that change makes sense, I wonder if there is a better way to handle it though, since most of the time most rules are already going to be up to date I wonder if we can differentiate that error from other errors and just ignore it instead? I'm okay with just this change for now though.
