### ISSUE TITLE
Small typo (rulesets)?

### ISSUE THREAD

**Issue by DanielRuf** [EFForg/yaya#21]
I guess this is a small typo but changing this may break existing setups:

https://github.com/EFForg/yaya/blob/master/yaya.go#L76

`var rulesetsPath = path.Join(configPath, "rulsets")`

**Comment by cooperq** [comment]
yes,  it would as you said. We could add some code to migrate but that seems like a lot of extra code and work just to fix a small typo. I'm okay with leaving it as is.

**Comment by DanielRuf** [comment]
> I'm okay with leaving it as is.

Me too. Thanks for taking the time to answer. Just wanted to clarify this so I understand it a bit better and if it was written like this intentionally.
