### ISSUE TITLE
Changed some imports to get YaYa working on Ubuntu 18.04

### ISSUE THREAD

**Issue by kirk-sayre-work** [EFForg/yaya#4]
This may be something unique to my setup, but I had to change 2 import statements to get YaYa working on my Ubuntu 18.04.4 LTS machine.

The 1st issue was with the "github.com/go-git/go-git" import. I ran into the problem discussed at https://github.com/src-d/go-git/issues/914 with this import and had to change it to "gopkg.in/src-d/go-git.v4" to fix the issue.

The 2nd issue was a version problem with go-yara. I changed "github.com/hillu/go-yara" to "github.com/hillu/go-yara/v4" to fix this issue. 

Once I made those changes everything worked perfectly.

**Comment by dadokkio** [comment]
I had similar issue with different OS and different go release.
In my case everything was fine with go release 1.15, while I had issue with older or newer release.
This morning go 1.16 has been pushed to my ubuntu 20.04 and I had to debug a little to make everything working again.

**Comment by cooperq** [comment]
interesting, can you specify the steps you took to fix it? I will also try to reproduce on my end.

**Comment by dadokkio** [comment]
Directly from my bash history:

```
go version
--> go version go1.16 linux/amd64

go get github.com/EFForg/yaya
cd ../go/src/github.com/EFForg/yaya/
go build 
---> error, missing init

go mod init 
---> error, missing tidy

go mod tidy
go mod init
go build 
---> it tries to download both go-yara v3 and v4, then fails because it wants v4 

vi yaya.go 
---> changing go-git and go-yara to go-git.v4 and go-yara/v4

vi utils.go 
---> changing go-yara to go-yara/v4

go build
---> success :smile: 
```

With go 1.15 is just ok a single `go build` instead

**Comment by cooperq** [comment]
interesting, must have been some pretty big changes in go1.16 I will have to look into this. Ideally I will be able to find a way where just a `go build` will work in 1.15 and 1.16.

**Comment by dasdboot** [comment]
Just do 
export GO111MODULE=off
after that, all is magically fixed and works with go1.16
leaving it here for posterity, it took me a while to figure it out
